# Generated by Django 5.0.1 on 2026-01-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_feedback',
            field=models.TextField(blank=True, help_text='Feedback from driver after delivery', null=True),
        ),
    ]
